name: robomimic_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fonttools=4.53.1=py38h2019614_0
  - freetype=2.14.1=ha770c72_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.19=hd590300_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=4.24.4=hf27288f_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.7=h4922eb0_0
  - lxml=5.3.0=py38hd8ce619_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - mkl=2022.2.1=h6508926_16999
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.4=py38h59b608b_0
  - openblas=0.3.30=pthreads_h6ec200e_4
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38h01efb38_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=10.0.1=py38h71741d6_1
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - sentry-sdk=2.19.2=pyhd8ed1ab_0
  - setproctitle=1.3.3=py38h01eb140_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sleef=3.9.0=ha0421bc_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sqlite=3.51.1=hbc0de68_0
  - statsmodels=0.14.1=py38h7f0c24c_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.13.0=h8d10470_4
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - typeguard=4.4.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py38h01eb140_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wandb=0.16.6=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cachetools==5.5.2
      - daqp==0.7.2
      - diffusers==0.11.1
      - egl-probe==1.0.2
      - evdev==1.9.2
      - fsspec==2025.3.0
      - google-auth==2.44.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - huggingface-hub==0.23.4
      - hydra-core==1.3.2
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - kiwisolver==1.4.7
      - llvmlite==0.41.1
      - markdown==3.7
      - matplotlib==3.7.5
      - mink==0.0.13
      - mujoco==3.2.3
      - numba==0.58.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pynput==1.8.1
      - pyopengl==3.1.10
      - python-xlib==0.33
      - pyyaml==6.0.3
      - qpsolvers==4.8.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - robosuite==1.5.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - six==1.17.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tokenizers==0.19.1
      - torch==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.67.1
      - transformers==4.41.2
      - triton==3.0.0
      - werkzeug==3.0.6
prefix: /home/pouyan/anaconda3/envs/robomimic_venv
